annotations:
  category: DevOps
apiVersion: v2
name: istio-cfg
description: Default configurations for istio

type: application

version: 0.1.0

appVersion: "1.0.0"

home: "https://github.com/adhoc-dev/helm-charts"
sources:
  - "https://github.com/adhoc-dev/"
maintainers:
  - name: dbollini
    email: dib@adhoc.inc
  - name: jjscarafia
    email: jjs@adhoc.inc
  - name: azacchino
    email: az@adhoc.inc

icon: "https://github.com/adhoc-dev/helm-charts/raw/main/img/istio.png"
