apiVersion: v2
kind: Service
metadata:
  name: {{ include "adhoc-redis.fullname" . }}
  labels:
    {{- include "adhoc-redis.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "adhoc-redis.selectorLabels" . | nindent 4 }}
