annotations:
  category: DevOps
apiVersion: v2
name: kwkhtmltopdf
description: KW KHTML to PDF Chart

type: application

version: 0.0.1

home: "https://github.com/adhoc-dev/helm-charts"
sources:
  - "https://github.com/adhoc-dev/"
maintainers:
  - name: dbollini
    email: dib@adhoc.inc
  - name: jjscarafia
    email: jjs@adhoc.inc
  - name: azacchino
    email: az@adhoc.inc

icon: "https://github.com/adhoc-dev/helm-charts/raw/main/img/weblate.png"
