{{- if or .Values.odoo.monitoring.enabled .Values.ingress.reverseProxy.monitoring.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "adhoc-odoo.fullname" . }}-allow-prometheus
  labels:
    {{- include "adhoc-odoo.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ include "adhoc-odoo.fullname" . }}
  policyTypes:
    - Ingress
  {{- if or .Values.ingress.reverseProxy.monitoring.enabled .Values.odoo.monitoring.enabled }}
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: monitoring
      ports:
      {{- if .Values.ingress.reverseProxy.monitoring.enabled }}
        - port: 9113
          protocol: TCP
        - port: 9114
          protocol: TCP
      {{- end }}
      {{- if .Values.odoo.monitoring.enabled }}
        - port: 8069
          protocol: TCP
      {{- end }}
  {{- end }}
{{- end }}
