apiVersion: v1
kind: Service
metadata:
  name: {{ include "adhoc-odoo.fullname" . }}-http
  labels:
    {{- include "adhoc-odoo.labels" . | nindent 4 }}
  {{- if .Values.ingress.useGoogleCloudExternalLB }}
  annotations:
    beta.cloud.google.com/backend-config: {{ include "adhoc-odoo.fullname" . }}-backend-config
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "adhoc-odoo.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "adhoc-odoo.fullname" . }}-websocket
  labels:
    {{- include "adhoc-odoo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: websocket
      protocol: TCP
      name: websocket
  selector:
    {{- include "adhoc-odoo.selectorLabels" . | nindent 4 }}
