image:
  repository: weblate/weblate
  pullPolicy: IfNotPresent
  tag: "5.10"

cron:
  image:
    repository: dockerhub.adhoc.inc/adhoc/weblate
    tag: "5.10-ext"

cloudNativePG:
  superUserPassword: "please-fill-with-secure-password"
  version: "15.0"
  persistence:
    size: 1
    storageClass: "gpc-ssd-d"
  backup:
    volumeSnapshot:
      volumeSnapshotClass: gcp-r

ingress:
  host: "translation.example.com"
  issuer: "prod-issuer"

nodeTag: "Prod"

weblate:

weblateGenerator:
  sshPub: "ssh ..... weblate"
  sshPriv: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    -----END OPENSSH PRIVATE KEY-----
    
# The new line is important!


