annotations:
  category: DevOps
apiVersion: v2
name: adhoc-redis
description: "Redis for odoo sessions"

type: application

version: 0.1.2

appVersion: "6-alpine"

home: "https://github.com/adhoc-dev/helm-charts"
sources:
  - "https://github.com/adhoc-dev/"
maintainers:
  - name: dbollini
    email: dib@adhoc.com.ar
  - name: jjscarafia
    email: jjs@adhoc.com.ar

icon: "https://github.com/adhoc-dev/helm-charts/raw/main/img/Redis_Logo.svg"
