{{- if .Values.ingress.reverseProxy.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "adhoc-odoo.fullname" . }}-odoo-sendfile-conf
  labels:
    {{- include "adhoc-odoo.labels" . | nindent 4 }}
data:
  odoo-send-file.conf: |
    [options]
      x_sendfile = True
      report.url = http://{{ include "adhoc-odoo.serviceNameSuffix" . }}-nginx.{{ .Release.Namespace }}.svc.cluster.local
{{- end }}
