{{- if and .Values.ingress.reverseProxy.enabled .Values.ingress.reverseProxy.monitoring.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "adhoc-odoo.fullname" . }}-nx
  labels:
    release: prom
spec:
  selector:
    matchLabels:
      {{- include "adhoc-odoo.nxselectorLabels" . | nindent 8 }}
  podMetricsEndpoints:
    - port: prom-nx
      interval: 60s
    - port: prom-nx-log
      interval: 60s
{{- end }}
