annotations:
  category: DevOps
apiVersion: v2
name: adhoc-aeroo-docs
description: A document conversion service (.odt to .pdf for reports)

type: application

version: 0.1.2

appVersion: "1.16.0"

home: "https://github.com/adhoc-dev/helm-charts"
sources:
  - "https://github.com/adhoc-dev/"
maintainers:
  - name: dbollini
    email: dib@adhoc.com.ar
  - name: jjscarafia
    email: jjs@adhoc.com.ar

icon: "https://github.com/adhoc-dev/helm-charts/raw/main/img/aerooIcon.png"
