{{- if .Values.cloudNativePG.enabled }}
{{- if .Values.cloudNativePG.restore.fromGCPSnapshot }}

# Class
{{- $volumeSnapshotClass := default "gcp-r" .Values.cloudNativePG.restore.volumeSnapshotClass }}
{{- $targetBkp := ( include "cnpg.targetBkp" . ) }}

apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotContent
metadata:
  name: {{ printf "%s-%s" .Release.Namespace $targetBkp }}
  labels:
    {{- include "adhoc-odoo.labels" . | nindent 4 }}
spec:
  deletionPolicy: Retain
  driver: pd.csi.storage.gke.io
  source:
    snapshotHandle: {{ .Values.cloudNativePG.restore.fromGCPSnapshot | quote }}
  volumeSnapshotRef:
    name: {{ $targetBkp }}-vs
    namespace: {{ .Release.Namespace }}
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: {{ $targetBkp }}-vs
  namespace: {{ .Release.Namespace }}
  annotations:
    cnpg.io/pvcRole: PG_DATA
  labels:
    {{- include "adhoc-odoo.labels" . | nindent 4 }}
    cnpg.io/backupName: {{ $targetBkp | quote }}
spec:
  volumeSnapshotClassName: {{ $volumeSnapshotClass }}
  source:
    volumeSnapshotContentName: {{ printf "%s-%s" .Release.Namespace $targetBkp }}

{{- end }}
{{- end }}