apiVersion: v1
kind: Service
metadata:
  name: {{ include "adhoc-odoo.fullname" . }}-http
  labels:
    {{- include "adhoc-odoo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "adhoc-odoo.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "adhoc-odoo.fullname" . }}-longpolling
  labels:
    {{- include "adhoc-odoo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: longpolling
      protocol: TCP
      name: longpolling
  selector:
    {{- include "adhoc-odoo.selectorLabels" . | nindent 4 }}