apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "registry-cache.fullname" . }}-config
data:
  config.yml: |
    version: 0.1
    log:
      level: info
    http:
      addr: 0.0.0.0:5000
      debug:
        prometheus:
          enabled: true
          path: /metrics
    storage:
      filesystem:
        rootdirectory: /var/lib/registry
      maintenance:
        uploadpurging:
          enabled: true
          age: 1440h
          interval: 24h
          dryrun: false
        readonly:
          enabled: false
    proxy:
      remoteurl: {{ .Values.proxy.remoteurl | quote }}
      # Mark cached content as stale after 60 days
      ttl: 1440h
    tracing:
      enabled: false
