apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "registry-cache.fullname" . }}
spec:
  serviceName: {{ include "registry-cache.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "registry-cache.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "registry-cache.name" . }}
        adhoc.ar/app-name: "registry-cache"
    spec:
      priorityClassName: registry-cache-priority
      nodeSelector: {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations: {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cloud.google.com/gke-spot
                    operator: NotIn
                    values:
                      - "true"
        {{- if .Values.affinity }}
        {{- toYaml .Values.affinity | nindent 8 }}
        {{- end }}
      containers:
        - name: registry
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            limits:
              cpu: 500m
              memory: 4Gi
            requests:
              cpu: 250m
              memory: 1Gi
          ports:
            - containerPort: 5000
          env:
            - name: OTEL_TRACES_EXPORTER
              value: "none"
            - name: OTEL_METRICS_EXPORTER
              value: "none"
            - name: OTEL_LOGS_EXPORTER
              value: "none"
            {{- if .Values.proxy.auth.enabled }}
            - name: REGISTRY_PROXY_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "registry-cache.fullname" . }}-dockerhub-auth
                  key: REGISTRY_PROXY_USERNAME
            - name: REGISTRY_PROXY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "registry-cache.fullname" . }}-dockerhub-auth
                  key: REGISTRY_PROXY_PASSWORD
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/distribution
            {{- if .Values.storage.filesystem.enabled }}
            - name: data
              mountPath: /var/lib/registry
            {{- end }}
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 30
          resources: {{- toYaml .Values.resources | nindent 12 }}
        - name: cleaner
          image: busybox:1.36
          command:
            - /bin/sh
            - -ec
            - |
              THRESHOLD=${DISK_THRESHOLD:-70}
              # Time to live for blobs, in days
              TTL_DAYS=${TTL_DAYS:-7}
              # Sleep for a day by default between checks 86400 seconds = 24 hours
              SLEEP_INTERVAL=${SLEEP_INTERVAL:-86400}

              echo "started with threshold=${THRESHOLD}% ttl=${TTL_DAYS}d interval=${SLEEP_INTERVAL}s"

              while true; do
                used=$(df -P /var/lib/registry | awk 'NR==2 {print $5}' | tr -d '%')
                echo "disk usage: ${used}%"

                if [ "$used" -ge "$THRESHOLD" ]; then
                  echo "threshold exceeded (${used}% > ${THRESHOLD}%), cleaning old blobs..."
                  find /var/lib/registry/docker/registry/v2/blobs/sha256 -type f -mtime +${TTL_DAYS} -print -delete

                  echo "restart main registry container..."
                  kill 1
                else
                  echo "disk usage under threshold, skipping cleanup."
                fi

                echo "sleeping ${SLEEP_INTERVAL}s..."
                sleep "${SLEEP_INTERVAL}"
              done
          env:
            - name: DISK_THRESHOLD
              value: "70"
            - name: TTL_DAYS
              value: "61"
            - name: SLEEP_INTERVAL
              value: "86400" # 24h
          resources:
            limits:
              cpu: 50m
              memory: 128Mi
            requests:
              cpu: 5m
              memory: 32Mi
          volumeMounts:
            {{- if .Values.storage.filesystem.enabled }}
            - name: data
              mountPath: /var/lib/registry
            {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "registry-cache.fullname" . }}-config
            items:
              - key: config.yml
                path: config.yml
        {{- if .Values.storage.filesystem.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "registry-cache.fullname" . }}-data
      # TODO: Use volumeClaimTemplates for StatefulSet and remove PVC.yaml reference
      # volumeClaimTemplates:
      #   - metadata:
      #       name: data
      #     spec:
      #       accessModes: ["ReadWriteOnce"]
      #       resources:
      #         requests:
      #           storage: {{ .Values.storage.size | default "10Gi" }}
      #       storageClassName: {{ .Values.storage.class | default "standard-rwo" | quote }}
        {{- end }}
