apiVersion: v1
kind: Service
metadata:
  name: {{ include "registry-cache.fullname" . }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "registry-cache.name" . }}
  ports:
    - name: http
      port: 5000
      targetPort: 5000
