{{- if and .Values.ingress.reverseProxy.enabled .Values.ingress.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "adhoc-odoo.serviceNameSuffix" . }}-nginx
  labels:
    {{- include "adhoc-odoo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.ingress.reverseProxy.monitoring.enabled }}
    - port: 9113
      targetPort: 9113
      protocol: TCP
      name: metrics
    - port: 9114
      targetPort: 9114
      protocol: TCP
      name: metrics-log
    {{- end }}
  selector:
    {{- include "adhoc-odoo.nxselectorLabels" . | nindent 4 }}
{{- end }}