{{- if .Values.proxy.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "registry-cache.fullname" . }}-dockerhub-auth
type: Opaque
stringData:
  REGISTRY_PROXY_USERNAME: {{ required "proxy.auth.username required" .Values.proxy.auth.username | quote }}
  REGISTRY_PROXY_PASSWORD: {{ required "proxy.auth.password required" .Values.proxy.auth.password | quote }}
{{- end }}
