{{- $odooVersion := include "adhoc-odoo.odoo-version" . | replace "." "" | int -}}
{{- if ge $odooVersion 190 }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "adhoc-odoo.fullname" . }}-odoo-extra-conf
  labels:
    {{- include "adhoc-odoo.labels" . | nindent 4 }}
data:
  odoo-extra.conf: |
    [options]
      log_handler = :INFO,odoo.addons.rpc.controllers.jsonrpc:ERROR
{{- if not .Values.ingress.reverseProxy.enabled }}
      report.url = http://{{ include "adhoc-odoo.serviceNameSuffix" . }}-http.{{ .Release.Namespace }}.svc.cluster.local
{{- end }}
{{- end }}