apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app-instance.fullname" . }}-ssh-keys
type: Opaque
data:
  id_ed25519: {{ .Values.weblateGenerator.sshPriv | b64enc }}
  id_ed25519.pub: {{ .Values.weblateGenerator.sshPub | b64enc }}
